version: '3'
services:
  mongo:
    image: mongo:4.2
    container_name: mongo
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  app:
    build: .
    environment:
      MONGO_URI: mongo
    ports:
      - 5000:5000
