name: release to dockerhub

on:
  push:
    branches:
    - master

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: jdassonvil
      APP: simple-python
    steps:
    - uses: actions/checkout@v2
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: "${{ env.DOCKERHUB_USERNAME }}/${{ env.APP }}:latest,${{ env.DOCKERHUB_USERNAME }}/${{ env.APP }}:${{ steps.vars.outputs.sha_short }}"
